name: shellcheck
on: [push]
jobs:
  Step1:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run shellcheck
        run: |
          sudo apt install -y shellcheck
          shellcheck upgrade.sh
